-- 테이블 생성 SQL - 테이블명 적기!
CREATE TABLE A_MEMBER(

);

-- USER_INFO TABLE
CREATE TABLE USER_INFO(
USER_ID VARCHAR(20) NOT NULL,
USER_NAME VARCHAR(30) NOT NULL,
USER_NICK VARCHAR(20) NOT NULL,
PRIMARY KEY(USER_ID),
UNIQUE KEY(USER_NICK)
);

-- MODEL_INFO TABLE
CREATE TABLE MODEL_INFO(
MODEL_CODE VARCHAR(100) NOT NULL,
MODEL_NAME VARCHAR(50) NOT NULL,
MODEL_INFO VARCHAR(20),
MODEL_IMG VARCHAR(200) NOT NULL,
MODEL_DATE VARCHAR(10) NOT NULL,
MODEL_ROOT VARCHAR(100) NOT NULL,
PRIMARY KEY(MODEL_CODE)
);

-- IMG_INFO TABLE
CREATE TABLE IMG_INFO(
IMG_CODE VARCHAR(100) NOT NULL,
IMG_NAME VARCHAR(50) NOT NULL,
MODEL_CODE VARCHAR(100) NOT NULL,
MODEL_NAME VARCHAR(50) NOT NULL,
USER_ID VARCHAR(20) NOT NULL,
USER_NICK VARCHAR(20) NOT NULL,
IMG_PROMPT VARCHAR(500),
IMG_ORIGIN VARCHAR(200) NOT NULL,
PRIMARY KEY(IMG_CODE),
FOREIGN KEY(MODEL_CODE) REFERENCES MODEL(MODEL_CODE),
FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID),
);

