CREATE TABLE T_USER
(
    USER_ID      VARCHAR2(30)    NOT NULL, 
    USER_PW    VARCHAR2(30)    NOT NULL, 
    USER_NICK    VARCHAR2(20)    NOT NULL, 
    USER_PHONE VARCHAR2(30) NOT NULL,
    PRIMARY KEY (USER_ID),
);

select * from T_user